[global]
# If set to true, also look for and load .env files on top of the .envrc files.
# If both .envrc and .env files exist, the .envrc  will  always  be  chosen first.
load_dotenv = true

# If set to true, the .envrc will be loaded with set -euo pipefail. This option
# will be the default in the future.
strict_env = true

# Set to true to hide the diff of the environment variables when loading the .envrc.
# Defaults to false.
hide_env_diff = false
